[build]
  command = "pip install -r netlify/functions/youtube-transcript/requirements.txt -t python"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["youtube-transcript-api"]

[[redirects]]
  from = "/api/transcript"
  to = "/.netlify/functions/youtube-transcript/transcript.py"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
