[build]
  command = "./netlify-build.sh"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20.11.1"
  NPM_VERSION = "10.2.4"
  NODE_OPTIONS = "--max_old_space_size=4096"
  CI = "false"
  NPM_FLAGS = "--legacy-peer-deps"
  NPM_CONFIG_LEGACY_PEER_DEPS = "true"
  NODE_VERBOSE = "true"
  
[dev]
  framework = "#custom"
  command = "npm run dev"
  targetPort = 8080
  port = 8888

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@google-cloud/text-to-speech", "@googleapis/youtube"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.googletagmanager.com https://www.google-analytics.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https://*.googleapis.com https://*.supadata.ai;"
